org: jjmar
app: game-deals-notifier
service: game-deals-notifier

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverless
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - ${env:BUCKET_NAME}
                - '/*'
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - ${env:BUCKET_NAME}
        - Effect: 'Allow'
          Action:
            - 'sns:Publish'
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:sns:us-east-1:'
                - ${aws:accountId}
                - ':'
                - ${env:TOPIC_NAME}

  environment:
    REDDIT_CLIENT_ID: ${env:REDDIT_CLIENT_ID}
    REDDIT_CLIENT_SECRET: ${env:REDDIT_CLIENT_SECRET}
    USER_AGENT: ${env:USER_AGENT}
    BUCKET_NAME: ${env:BUCKET_NAME}
    LAST_DEAL_FILENAME: ${env:LAST_DEAL_FILENAME}
    TOPIC_ARN: arn:aws:sns:us-east-1:${aws:accountId}:${env:TOPIC_NAME}

resources:
  Resources:
    lastSavedDealStore:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
    dealsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${env:TOPIC_NAME}

functions:
  notifier:
    handler: handler.run
    events:
      - schedule: rate(2 hours)
