org: jjmar
app: game-deals-notifier
service: game-deals-notifier

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverless
  environment:
    REDDIT_CLIENT_ID: ${env:REDDIT_CLIENT_ID}
    REDDIT_CLIENT_SECRET: ${env:REDDIT_CLIENT_SECRET}
    USER_AGENT: ${env:USER_AGENT}
    BUCKET_NAME: ${env:BUCKET_NAME}

resources:
  Resources:
    lastSavedDealStore:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

functions:
  notifier:
    handler: handler.run
    events:
      - schedule: rate(2 hours)
